version: "3.7"

services:
  mavkaapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: landing-wagtail-app
    command: sh runserver.sh
    volumes:
      - .:/app
    expose:
      - 8080
#    env_file:
#      - env/app.env
#      - env/database.env


  nginx:
    image: library/nginx:latest
    container_name: docker-mavka-nginx
    ports:
      - "8082:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    depends_on:
      - mavkaapp