# Generated by Django 4.1.8 on 2023-04-21 20:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='event_block',
            field=wagtail.fields.StreamField([('projects_block', wagtail.blocks.StructBlock([('title_events', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('event_card', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=300, required=False)), ('description', wagtail.blocks.CharBlock(max_length=300, required=False)), ('event_url', wagtail.blocks.URLBlock(help_text='Link URL.', required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
