# Generated by Django 4.1.8 on 2023-05-16 10:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_event_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='event_block',
            field=wagtail.fields.StreamField([('projects_block', wagtail.blocks.StructBlock([('title_events', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('title_text1', wagtail.blocks.CharBlock(help_text='Add title text1', required=True)), ('title_text2', wagtail.blocks.CharBlock(help_text='Add title text2', required=True)), ('event_card', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('date', wagtail.blocks.DateBlock(required=False)), ('title', wagtail.blocks.CharBlock(max_length=300, required=False)), ('event_url', wagtail.blocks.URLBlock(help_text='Link URL.', required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
