# Generated by Django 4.1.9 on 2023-05-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_facts_block_alter_homepage_event_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_text',
            field=models.TextField(blank=True),
        ),
    ]
