# Generated by Django 4.1.8 on 2023-05-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitespecificsocialmediasettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
